# Generated by Django 4.2.4 on 2023-08-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hongtingapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='group_size',
            field=models.CharField(choices=[('1', '소개팅'), ('2', '2명이서'), ('3', '3명이서'), ('4', '4명이서')], max_length=100),
        ),
    ]
