# Generated by Django 4.2.4 on 2023-08-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hongtingapp', '0002_remove_userprofile_age_remove_userprofile_extra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='group_size',
            field=models.CharField(choices=[('1', '소개팅'), ('2', '2명이서'), ('3', '3명이서'), ('4', '4명이서')], max_length=10000),
        ),
    ]
